### ISSUE TITLE
[Question]: Any reason for not to use enum to represent code type?

### ISSUE THREAD

**Issue by ENvironmentSet** [cyclejs/callbags#1]
https://github.com/cyclejs/callbags/blob/c0247125897001d2252d4fec18b9444b5d9b0f18/src/types.ts#L1-L5

Currently, we're using couple of plain types to represent code type.
IMO, It would be better if we use enum to do so for these reasons:

1. Typings became more meaningful

```typescript
enum Code {
  START,
  DATA,
  END,
}
```

is better than just spreading plain types.

2. Increase code readability in term level

Instead of using numeric constants(whose shape is very odd) like `0`, `1` to represent code,
we can use constants like `Code.START` when we write code.
And this will make our code more readable.

Is there any reason not to use enum to represent code type?
Please let me know if it exist. :)

**Comment by jvanbruegge** [comment]
Performance mainly. Such an enum would be compiled down to this:
```js
export var Code;
(function (Code) {
    Code[Code["START"] = 0] = "START";
    Code[Code["DATA"] = 1] = "DATA";
    Code[Code["END"] = 2] = "END";
})(Code || (Code = {}));
//# sourceMappingURL=types.js.map
```
And every mention of `Code.something` is now a lookup in an object. And you don't really need an enum if you don't want plain `0`, `1`, and `2`. You could defined constants for that named `START`, `DATA` and `END`.
But personally I don't really have a problem with plain numbers
