### ISSUE TITLE
Callbag type and Subject type

### ISSUE THREAD

**Issue by staltz** [cyclejs/callbags#11]
Currently

```typescript
type Callbag<T> = (t: ALL, d?: Talkback | T | any) => void;
```

the `d: Talkback` means that if we call this callbag with `(0, talkback)` then the given `talkback` can never be called with `0` or `1`, but that happens in `src/subject.ts`:

```typescript
import { Callbag, ALL } from './types';

export function makeSubject<T>(): Callbag<T> {
  let sinks: any[] = [];

  return (type: ALL, data: any) => {
    if (type === 0) {
      const sink = data; // this sink *would* be typed Talkback and 
                         // thus we shouldn't call `sink(0, ...)`          
      sinks.push(data);
      sink(0, () => {
        const i = sinks.indexOf(sink);
        sinks[i] = void 0;
      });
    } else {
      let hasDeleted = false;

      for (let i = 0; i < sinks.length; i++) {
        if (sinks[i]) sinks[i](type, data);
        else hasDeleted = true;
      }

      if (hasDeleted) {
        sinks = sinks.filter(x => x !== undefined);
      }
    }
  };
}
```

This is kind of a non-problem, though, because the `any` dominates in `d?: Talkback | T | any`. But it doesn't make semantic sense.

**But** we don't use Callbag for anything else than typing the Subject, so how about we just rename it to `Subject`? And because of that we can type the Subject type correctly so that it can:

- Receive sinks (not talkbacks) when `t=0`
- Receive data when `t=1`
- Receive `t=2`

The (outward-facing) `Subject` type might be very soon important for implementation of the new Cycle run.

**Comment by jvanbruegge** [comment]
Yeah, I agree with this. Subject does not return a Callbag in our sense, but a Producer that can also handle 1s and 2s

**Comment by staltz** [comment]
I'm sketching something. So far I got:

```typescript
export type Sink<T> = {
  (t: START, d: Talkback): void;
  (t: DATA, d: T): void;
  (t: END, d: unknown): void;
  // (t: END): void;
}

export type Subject<T> = {
  (t: START, d: Sink<T>): void;
  (T: DATA, d: T): void;
  (t: END, d: unknown): void;
  // (t: END): void;
}
```

Note the `Sink<T>` type doesn't need to actually be exported. Plus, it can be used to type the producer as

```typescript
type Producer<T> = (t: START, sink: Sink<T>) => void;
```

(Or are we forced to export Sink since Producer will be public?)

**Comment by jvanbruegge** [comment]
I think you have to export it, but that's not a problem, it should stay mostly internal.
Just your types as they are probably won't work because of the lacking type inference, but we can union them manually like the Callbag type at the moment

**Comment by staltz** [comment]
Hmm yeah maybe for `Producer` we can use `WeakSink` or something like that, which uses the union. And then just for Subject we use `Sink`.

Or the other way around:

- Producer uses `Sink`
- Subject uses `StrongSink`

**Comment by jvanbruegge** [comment]
I guess we just have to try what works. We use subject in the tests, so we should be alerted about unforseen consequences

**Comment by staltz** [comment]
And can I update the type of `pipe` to accept `Source | Subject` ? (removing Callbag)

**Comment by jvanbruegge** [comment]
Sure that was always meant for the Subject anyways
