### ISSUE TITLE
Non-blocking callbag question

### ISSUE THREAD

**Issue by delaneyj** [cyclejs/callbags#20]
So in trying to understand callbags, especially in native typescript better I started implementing a non-blocking version of interval which didn't work but the blocking version did.  Obviously don't want to lock up other code waiting on an interval.  What am I missing in the non-blocking version?

```ts
import { Producer, END } from './types';

export function intervalNonblocking(ms: number): Producer<number> {
  return (_, sink) => {
    let id: NodeJS.Timeout;
    let i = 0;

    id = setInterval(() => {
      sink(1, i);
      i++;
    }, ms);

    sink(0, (_: END) => {
      clearTimeout(id);
    });
  };
}

export function intervalBlocking(ms: number): Producer<number> {
  return (_, sink) => {
    let ended = false;

    sink(0, (_: END) => {
      ended = true;
    });

    let lastTime = Date.now();
    let i = 0;
    while (!ended) {
      const now = Date.now();
      const delta = now - lastTime;
      if (delta >= ms) {
        sink(1, i++);
        lastTime = now;
      }
    }
  };
}

```

**Comment by jvanbruegge** [comment]
what is not working? the code looks correct

**Comment by delaneyj** [comment]
I added test to the project and it exits out early.
 
```
import { interval, take, pipe, subscribe } from '../src/index';

describe('interval', () => {
  it('should allow to terminate early', () => {
    let taken = 0;

    pipe(
      interval(1000),
      take(2),
      subscribe(() => {
        taken++;
      })
    );

    assert.strictEqual(taken, 2);
  });
});
```

Getting `AssertionError [ERR_ASSERTION]: Expected values to be strictly equal: 0 !== 2`. 

Thank for rubber ducking.... that not going work at all. Needed to use the callback in mocha.

```
describe('interval', () => {
  it('should allow to terminate early', done => {
    let taken = 0;

    pipe(
      interval(1000),
      take(2),
      subscribe(
        () => {
          taken++;
        },
        () => {
          assert.strictEqual(taken, 2);
          done();
        }
      )
    );
  });
});
```

Are you looking for contributions for operators or trying to keep as trim as possible?  Need things based on time, exponential back off, etc and seeing if I should try to PR them back.

**Comment by jvanbruegge** [comment]
The operators here are mostly to work for the internals of cyclejs. We explicitly don't add time-based operators, because they should be implemented in terms of a time driver. For contributions it's best to put them in your own repo and publish them seperately. `pipe` works with any standard callbag so you can seamlessly interoperate

**Comment by jvanbruegge** [comment]
For backpressure, the use case would be interesting and what the source should do in that case, pleolase open a second issue for discussion about this
